In [1]:
# activate line execution
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# general
import numpy as np
import pandas as pd
import math
# import matplotlib.pyplot as plt
import os
import shutil
import pickle

# plotly
import plotly.express as px  # (version 4.7.0 or higher)
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import matplotlib.pyplot as plt

# import custom libraries
import sys
# sys.path.append("C:\\DATA\\Tasks\\lib\\hk")
# import hk_utils

# folder paths
ADD_DATA = "C:\\DATA\\data\\raw\\mimic4\\lookup\\"
ADD_DATA_proc = "C:/DATA/data/processed/"


PATH_PAPER = "C:\\DATA\\Tasks\\220704\\Alternate-Transactions-Articles-LaTeX-template\\images\\"


PATH_SYS="/mlodata1/hokarami/tedam/"

In [2]:
# libraries for THP

import argparse
import numpy as np
import pickle
import time
import torch
import torch.nn as nn
import torch.optim as optim
# from torch.utils.tensorboard import SummaryWriter

import transformer.Constants as Constants
import Utils

# from preprocess.Dataset import get_dataloader, get_dataloader2
# from transformer.Models import Transformer
# from transformer.hk_transformer import Transformer
from tqdm import tqdm

# from torchinfo import summary

os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

# torch.cuda.empty_cache()
# torch.cuda.memory_allocated()
# torch.cuda.memory_reserved()

from sklearn import metrics
# from hk_pytorch import save_checkpoint,load_checkpoint
# import hk_pytorch


# from custom2 import myparser
import re

/opt/conda/envs/paper2022/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
import Main
import webbrowser


In [4]:
import io

In [5]:
from scipy import integrate

In [6]:
# sudo conda install -c conda-forge dash --name paper2022
# sudo conda install -c conda-forge jupyter-dash --name paper2022

In [7]:
from tsnecuda import TSNE
from MulticoreTSNE import MulticoreTSNE as TSNE

In [8]:
# !pip install wandb -qqq
import wandb
# wandb.login()
api = wandb.Api()
import os

os.environ["WANDB_API_KEY"] = "0f780ac8a470afe6cb7fc474ff3794772c660465"

os.environ["WANDB_NOTEBOOK_NAME"] = "jup_res"

# Functions

In [9]:
import io
import base64
import pickle
import gzip

import numpy as np

from jupyter_dash import JupyterDash
from dash import dcc, html, Input, Output, no_update
import dash_bootstrap_components as dbc
# sudo conda install -c conda-forge dash-bootstrap-components --name paper2022

import plotly.graph_objects as go

from PIL import ImageDraw, Image

from sklearn.manifold import TSNE

# Helper functions
def np_image_to_base64(im_matrix,scale=4):

    im_matrix = np.repeat(np.repeat(im_matrix,scale,axis=0),scale,axis=1)
    im = Image.fromarray(im_matrix)
    buffer = io.BytesIO()
    im.save(buffer, format="jpeg")
    encoded_image = base64.b64encode(buffer.getvalue()).decode()
    im_url = "data:image/jpeg;base64, " + encoded_image
    return im_url




def binary_matrix_to_image(binary_matrix, grid_size=8, border_size=1):
    # Calculate the size of the output image based on the size of the binary matrix
    height, width = binary_matrix.shape[:2]
    image_width = width * grid_size + (width + 1) * border_size
    image_height = height * grid_size + (height + 1) * border_size
    
    # Create a new image and a draw object to draw the grid and borders
    image = Image.new('RGB', (image_width, image_height), color='black')
    draw = ImageDraw.Draw(image)
    
    # Draw the white grids
    for i in range(height):
        for j in range(width):
            if binary_matrix[i, j] == 1:
                x1 = j * (grid_size + border_size) + border_size
                y1 = i * (grid_size + border_size) + border_size
                x2 = x1 + grid_size
                y2 = y1 + grid_size
                draw.rectangle((x1, y1, x2, y2), fill='white')
                
    
    # Draw the black borders
    for i in range(height + 1):
        y = i * (grid_size + border_size)
        draw.line((0, y, image_width, y), fill='white', width=border_size)
        
    for j in range(width + 1):
        x = j * (grid_size + border_size)
        draw.line((x, 0, x, image_height), fill='white', width=border_size)
        
    return image

In [10]:
def map_to_rgb(num, **rgb_params):
    
    
    
    if len(rgb_params)>0:

        normalized = (num - rgb_params['offset'])/rgb_params['range']

        
        # Map to a color between blue, gray, and red
        rgb_lower = rgb_params['rgb_lower']
        rgb_middle = rgb_params['rgb_middle']
        rgb_upper = rgb_params['rgb_upper']
    else:
    
        # Normalize to the range of 0 to 1
    
    
    
        normalized = (num + 2) / 4
        
        # Map to a color between blue, gray, and red
        rgb_lower = (0, 0, 255,1)
        rgb_middle = (128, 128, 128,1)
        rgb_upper = (255, 0, 0,1)
    
    if normalized < 0.5:
        r = int((2 * normalized) * rgb_middle[0] + (1 - 2 * normalized) * rgb_lower[0])
        g = int((2 * normalized) * rgb_middle[1] + (1 - 2 * normalized) * rgb_lower[1])
        b = int((2 * normalized) * rgb_middle[2] + (1 - 2 * normalized) * rgb_lower[2])
        a = int((2 * normalized) * rgb_middle[3] + (1 - 2 * normalized) * rgb_lower[3])
    else:
        r = int((2 * normalized - 1) * rgb_upper[0] + (2 - 2 * normalized) * rgb_middle[0])
        g = int((2 * normalized - 1) * rgb_upper[1] + (2 - 2 * normalized) * rgb_middle[1])
        b = int((2 * normalized - 1) * rgb_upper[2] + (2 - 2 * normalized) * rgb_middle[2])
        a = int((2 * normalized - 1) * rgb_upper[3] + (2 - 2 * normalized) * rgb_middle[3])
    
    # if normalized>0.5:
    #     print(normalized,a,rgb_upper[3])
    #     term
    return (r, g, b,a)


In [11]:
import numpy as np
from PIL import ImageDraw, Image, ImageFont

def binary_matrix_to_image(binary_matrix, row_labels=None, font_path=None, grid_size=10, border_size=1, label_size=15, is_fill=True,**rgb_params):
    # Add a dummy column to the binary matrix
    ddd=2

    height, width = binary_matrix.shape[:2]
    binary_matrix = np.concatenate((np.zeros((height, ddd)), binary_matrix), axis=1)
    width += ddd
    
    # Calculate the size of the output image based on the size of the binary matrix
    image_width = (width + 1) * grid_size + (width + 2) * border_size
    image_height = height * grid_size + (height + 1) * border_size
    
    # Create a new image and a draw object to draw the grid and borders
    image = Image.new('RGBA', (image_width, image_height), color=(0,0,0,0))
    draw = ImageDraw.Draw(image)
    
    # Draw the white grids
    for i in range(height):
        for j in range(1, width):
            # if binary_matrix[i, j] == 1:
            #     x1 = j * (grid_size + border_size) + border_size
            #     y1 = i * (grid_size + border_size) + border_size
            #     x2 = x1 + grid_size
            #     y2 = y1 + grid_size
            #     draw.rectangle((x1, y1, x2, y2), fill='white')

            if binary_matrix[i, j] != 0:
                x1 = j * (grid_size + border_size) + border_size
                y1 = i * (grid_size + border_size) + border_size
                x2 = x1 + grid_size
                y2 = y1 + grid_size

                int_color = ( int(binary_matrix[i, j]*96),
                             int(binary_matrix[i, j]*96),
                             int(binary_matrix[i, j]*96))

                
                int_color = map_to_rgb(binary_matrix[i, j], **rgb_params)
                if is_fill:
                    draw.rectangle((x1, y1, x2, y2), fill= int_color)
                else:
                    draw.rectangle((x1, y1, x2, y2), outline=int_color,width=2, fill= None)


    # Draw the borders
    color_border = (0,0,0,16)
    for i in range(height + 1):
        y = i * (grid_size + border_size)
        draw.line((grid_size, y, image_width, y), fill=color_border, width=border_size)
        
    for j in range(width + 1):
        x = j * (grid_size + border_size)
        draw.line((x, 0, x, image_height), fill=color_border, width=border_size)

    
    # Draw the row labels
    if row_labels is not None:
        font = ImageFont.truetype(PATH_SYS+'arial.ttf', size=label_size)
        max_label_width = max([font.getsize(str(label))[0] for label in row_labels])
        label_x = 0
        label_y = border_size
        for i, label in enumerate(row_labels):
            draw.text((label_x, label_y), str(label), font=font, fill='black',align="right")
            label_y += grid_size + border_size
            # if i == 0:
            #     label_x += max_label_width + border_size + grid_size
        
    return image


In [12]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

def create_barplot_image(data, labels, filename):
    """
    Creates a bar plot image of the input data and saves it as a PNG file with the given filename.

    Args:
        data (numpy.ndarray): A 1D array of data to plot.
        labels (list): A list of labels for each data point.
        filename (str): The name of the output PNG file.

    Returns:
        PIL.Image.Image: A PIL image object of the bar plot.
    """
    # Create a figure and axis object
    fig, ax = plt.subplots()

    # Create a bar plot
    _ = ax.bar(np.arange(len(data)), data)

    # Set axis labels and title
    _ = ax.set_xlabel('Index')
    _ = ax.set_ylabel('Value')
    _ = ax.set_title('Bar plot')

    # Set x-tick labels
    _ = ax.set_xticks(np.arange(len(data)))
    _ = ax.set_xticklabels(labels, rotation=45)

    # Save the plot as a PNG file
    _ = fig.savefig(filename)
    plt.close(fig)
    # Load the PNG image and return as a PIL image object
    return Image.open(filename)


In [13]:
def event2mat(event_type, event_time,P):

    m = event_type.sum(1)>0 # False are masked
    e=event_type[m,:]
    t=event_time[m]
    # print(t)

    indices = e.nonzero()
    indices[:,0] = t[indices[:,0]].int()
    # print(t[indices[:,0]])
    # print(indices[:,0])

    M = torch.zeros((P, e.shape[-1]))
    M[indices[:,0],indices[:,1]]=1

    return M.detach().cpu().numpy().transpose() # [M,P]

def att_event2mat(event_type, event_time,P, tee_att):
    # tee_att [h,L]
    h = tee_att.shape[0]

    m = event_type.sum(1)>0 # False are masked
    e=event_type[m,:]
    t=event_time[m]
    tee_att = tee_att[:,m]

    # indices = e.nonzero()
    # indices[:,0] = t[indices[:,0]].int()

    # M = torch.zeros(h, len(t))
    M = torch.zeros(( h , P))

    M[:,t.long()]=tee_att

    return M.detach().cpu().numpy() # [h,L]

In [14]:
def state2mat(time, mod,M):
    P = time.int().max().item() + 1

    M = torch.zeros(P, M)
    M[time[mod!=0].long(), mod[mod!=0]-1] = 1


    return M.cpu().numpy().transpose() # [M,P]

def att_state2mat(time, mod,M, dam_att):
    # dam_att [P,h]
    # h = dam_att.shape[-1]

    # dam_att = dam_att[:,0] # [P]
    P = time.int().max().item() + 1

    M = torch.zeros(P, M)
    
    M[time[mod!=0].long(),  mod[mod!=0]-1] = dam_att[mod!=0]


    return M.cpu().numpy().transpose() # [M,P]

## cool_image

In [15]:
def cool_image(out,i_b,i,opt,CROP=0):

    att_mat_img=None
    img_ev=None

    label_size = 12
    rgb_params_values = {
    'rgb_lower':(0, 0, 255,255),
    'rgb_middle':(128, 128, 128,255),
    'rgb_upper':(255, 0, 0,255),
    'offset':-2,
    'range':4

    }
    rgb_params_events = {
    'rgb_lower':(255, 255, 255,255),
    'rgb_middle':(196, 196, 196,255),
    'rgb_upper':(128, 128, 128,255),
    'offset':0,
    'range':1

    }
    rgb_params_events_pred = {
    'rgb_lower':(255, 255, 255,255),
    'rgb_middle':(128, 255, 128,255),
    'rgb_upper':(0, 255, 0,255),
    'offset':0,
    'range':1

    }
    # rgb_params_att = {
    #     'rgb_lower':(64, 64, 64,0),
    #     'rgb_middle':(164, 164, 32,32),
    #     'rgb_upper':(255, 255, 0,255),
    #     'offset':0,
    #     'range':0.1

    # }


    rgb_params_att = {
        'rgb_lower':(128, 128, 128,32),
        # 'rgb_middle':(8, 164, 32,196),
        'rgb_upper':(0, 255, 0,255),
        'offset':0,
        'range':0.2

    }


    rgb_params_att['rgb_middle'] = tuple([(int(i+j)/2) for i,j in zip(rgb_params_att['rgb_lower'],rgb_params_att['rgb_upper'])])
    rgb_params_att['rgb_middle']
    if hasattr(opt,'dict_map_states' ):
        state_labels = list(opt.dict_map_states.keys())[CROP:]
        state_labels = [str(i) for i in range(len(opt.dict_map_states))]

    if hasattr(opt,'dict_map_events' ):
        offset=len(opt.dict_map_states.keys())-len(opt.dict_map_events.keys())
        event_labels = list(opt.dict_map_events.keys())
        event_labels = [str(i+offset) for i in range(len(opt.dict_map_events))]


    # event_labels = opt.dict_map_events.keys()
    

    # if len(out['event_type_list']) > 0:
    

    if len(out['state_time_list']) > 0:
        st=out['state_time_list'][i_b][i]
        sm=out['state_mod_list'][i_b][i]
        sv=( out['state_value_list'][i_b][i] )

        dam_att = out['list_DAM_att'][i_b][i] # [P,h]

        n_state_mods = len(opt.dict_map_states.keys())

        # ev.shape, t.shape
        P = st.int().max().item() + 1

        
        # list_img_att = []
        # for i_head in range(dam_att.shape[-1]):
        #     binary_matrix = att_state2mat(st, sm, n_state_mods, dam_att[:,i_head])
        #     img_att = binary_matrix_to_image(binary_matrix, row_labels=state_labels, font_path=None, grid_size=10, border_size=1, label_size=label_size,is_fill=False,**rgb_params_att)
        #     list_img_att.append(img_att.convert("RGB"))

        binary_matrix = att_state2mat(st, sm, n_state_mods, dam_att.sum(1))[CROP:,:]
        # print(f'binary_matrix.shape={binary_matrix.shape}')
        
        img_att = binary_matrix_to_image(binary_matrix, row_labels=state_labels, font_path=None, grid_size=10, border_size=2, label_size=label_size,is_fill=False,**rgb_params_att)


        binary_matrix = att_state2mat(st, sm, n_state_mods, sv)[CROP:,:]
        img_val = binary_matrix_to_image(binary_matrix, row_labels=state_labels, font_path=None, grid_size=10, border_size=1, label_size=label_size,is_fill=True,**rgb_params_values)

        merged_img = Image.new('RGBA', img_val.size)
        merged_img = Image.alpha_composite(merged_img, img_val)
        # merged_img = Image.alpha_composite(merged_img, img_att)#.convert("RGB")

        if opt.event_enc:
            ev = out['event_type_list'][i_b][i]
            t = out['event_time_list'][i_b][i]
            
            ev_pred = out['next_event_type_list'][i_b][i]


            m = (ev.sum(1)>0).sum() # False are masked
            ev=ev[:m]
            ev_pred=ev_pred[:m-1] # for 2 to L-1
            ev_pred = nn.functional.pad(ev_pred,(0,0,1,0))
            t=t[:m]


            print(f'm={m}')

            print(f'ev.shape={ev.shape}')
            print(f'ev_pred.shape={ev_pred.shape}')

                                # plot attention of last event
            tee_att = out['list_TE_att'][i_b][i,:,m-1,:m] # [h,L]
            print(f'tee_att.shape={tee_att.shape}')
            # print(tee_att)
            

                                
            # att_names = [f'h{i}' for i in range(tee_att.shape[0])]
            # rgb_params_att['range']=tee_att.max()
            # binary_matrix = att_event2mat(ev, t,P, tee_att)

            # img_att_ev = binary_matrix_to_image(binary_matrix, row_labels=att_names, font_path=None, grid_size=10, border_size=1, label_size=label_size,is_fill=False,**rgb_params_att)
            
            # merged_img2 = Image.new('RGBA', (merged_img.size[0],merged_img.size[1]+img_att_ev.size[1]))
            # merged_img2.paste(merged_img, (0,0))
            # merged_img2.paste(img_att_ev, (0,merged_img.size[1]))
            # merged_img = merged_img2



                                # plot attention matrix
            m = (ev.sum(1)>0).sum() # False are masked
            tee_att_mat = out['list_TE_att'][i_b][i,:,:m,:m].mean(0) # [L,L]
            
            print(f'tee_att_mat.shape={tee_att_mat.shape}')
            
            # print(tee_att_mat.sum(1))
            scaler=torch.arange(1,m+1)[:,None]
            scaler= (1/tee_att_mat.max(1)[0])[:,None]
            tee_att_mat *= scaler
            rgb_params_att['range']=tee_att_mat.max()
            # print(tee_att_mat.max(1))

            # print(tee_att_mat[1])

            tee_att_mat_spaced = att_event2mat(ev, t,P, tee_att_mat)
            print(f'tee_att_mat_spaced.shape={tee_att_mat_spaced.shape}')

            binary_matrix = tee_att_mat_spaced
            img_val = binary_matrix_to_image(binary_matrix, row_labels=None, font_path=None, grid_size=10, border_size=1, label_size=label_size,is_fill=True,**rgb_params_att)

            att_mat_img = Image.new('RGBA', img_val.size)
            att_mat_img = Image.alpha_composite(att_mat_img, img_val)


            # t=torch.arange(m)
            # PP = t.int().max().item() + 1

            print(t[:m])
            ev_matrix = event2mat(ev,t,P)
            print(f'ev_matrix.shape={ev_matrix.shape}')
            print(P)
            img_ev = binary_matrix_to_image(ev_matrix, row_labels=event_labels, font_path=None, grid_size=10, border_size=1, label_size=label_size,**rgb_params_events)


            ev_pred_matrix = event2mat(ev_pred,t,P)
            print(f'ev_pred_matrix.shape={ev_pred_matrix.shape}')

            img_ev_pred = binary_matrix_to_image(ev_pred_matrix, row_labels=None, font_path=None, grid_size=10, border_size=1,is_fill=False, label_size=label_size,**rgb_params_events_pred)
            
            merged_img3 = Image.new('RGBA', (att_mat_img.size[0],att_mat_img.size[1]+img_ev.size[1]))
            merged_img3.paste(att_mat_img, (0,0))
            merged_img3.paste(img_ev, (0,att_mat_img.size[1]))
            merged_img3.paste(img_ev_pred, (0,att_mat_img.size[1]))

            temp_img = Image.new('RGBA', img_ev.size)
            temp_img = Image.alpha_composite(temp_img, img_ev)
            temp_img = Image.alpha_composite(temp_img, img_ev_pred)#.convert("RGB")

            merged_img3.paste(temp_img, (0,att_mat_img.size[1]))

            att_mat_img = merged_img3



    else:
        
        ev = out['event_type_list'][i_b][i]
        t = out['event_time_list'][i_b][i]
        P = t.int().max().item() + 1
        m = (ev.sum(1)>0).sum() # False are masked

        tee_att = out['list_TE_att'][i_b][i,:,m-2,:m] # [h,L]
        att_names = [f'h{i}' for i in range(tee_att.shape[0])]
        rgb_params_att['range']=tee_att.max()

        binary_matrix = event2mat(ev,t,P)
        img_ev = binary_matrix_to_image(binary_matrix, row_labels=event_labels, font_path=None, grid_size=10, border_size=1, label_size=label_size,**rgb_params_events)

        binary_matrix = att_event2mat(ev, t,P, tee_att)
        img_att_ev = binary_matrix_to_image(binary_matrix, row_labels=None, font_path=None, grid_size=10, border_size=1, label_size=label_size,is_fill=False,**rgb_params_att)
            
        # print(binary_matrix.sum())
        merged_img = Image.new('RGB', (img_ev.size[0],img_ev.size[1]+img_att_ev.size[1]))
        merged_img.paste(img_ev, (0,0))
        merged_img.paste(img_att_ev, (0,img_ev.size[1]))



        # plot attention matrix
        m = (ev.sum(1)>0).sum() # False are masked
        tee_att_mat = out['list_TE_att'][i_b][i,:,:m,:m].mean(0) # [L,L]

        binary_matrix = tee_att_mat
        img_val = binary_matrix_to_image(binary_matrix, row_labels=None, font_path=None, grid_size=10, border_size=1, label_size=label_size,is_fill=True,**rgb_params_att)
        
        att_mat_img = Image.new('RGBA', img_val.size)
        att_mat_img = Image.alpha_composite(att_mat_img, img_val)


    return merged_img,(att_mat_img,img_ev)#(img_att.convert("RGB"), img_val.convert("RGB"))

In [16]:
def bar_summary(df,out, point_ids,res_labels, fig=None):

    if fig is None:
        fig = go.Figure()



    list_summary = []
    for pid in point_ids:

        i_b = int(df.iloc[pid]['i_b'])
        i = int(df.iloc[pid]['i'])

        ev = out['event_type_list'][i_b][i]
        t = out['event_time_list'][i_b][i]
        

        P = t.int().max().item() + 1

        M = event2mat(ev,t,P)


        vector = M.sum(1)/M.shape[1]*24
        list_summary.append(vector)

    vec_mean = np.mean(list_summary,axis=0)
    vec_std = np.std(list_summary,axis=0)

    sum(vec_std)

    
    _ = fig.add_trace(go.Bar(
        name=f'Summary',
        x=list(res_labels), y=vec_mean,
        error_y=dict(type='data', array=vec_std)
    ))

    return fig

In [17]:
def read_from_wandb(run_path):

    run = api.run(run_path)
    for file in run.files():
        file.download(replace=True,root=f'./local/{run_path}/')

    opt = pickle.load(open(f'./local/{run_path}/opt.pkl','rb'))
    opt = Main.config(opt, justLoad=True)
    if not hasattr(opt,'diag_offset'):
        opt.diag_offset=1
        print('ATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT')
    checkpoint = torch.load(f'./local/{run_path}/best_model.pkl')

    model = Main.ATHP(
       n_marks=opt.num_marks,
        TE_config = opt.TE_config,
        DAM_config = opt.DAM_config,
        NOISE_config = opt.NOISE_config,

        CIF_config = opt.CIF_config,
        next_time_config = opt.next_time_config,
        next_type_config = opt.next_type_config,
        label_config = opt.label_config,

        demo_config = opt.demo_config,

        device=opt.device,
        diag_offset=opt.diag_offset
    )

    _ = model.to(opt.device)
    _ = model.load_state_dict(checkpoint['model_state_dict'])
    _ = model.eval()

    return model, opt, run

## summary

In [18]:
def find_knn_pids (X, id_origin, n_knn=10):

    # X [N,d] np.array
    r = np.sqrt(   ((X-X[id_origin])**2).sum(-1)   )
    knn_pids = list(np.argpartition(r,n_knn)[:n_knn])

    if id_origin not in knn_pids:
        print('bad')
    else:
        knn_pids.remove(id_origin)

    # print(X.shape)
    # term

    
    # x0 = df.iloc[id_origin]['x']
    # y0 = df.iloc[id_origin]['y']

    # df['r'] = df.apply(lambda row: ( (row['x']-x0)**2 + (row['y']-y0)**2  ), axis=1)

    # knn_pids = list(df.nsmallest(n_knn,'r').index)


    return knn_pids

def cal_similarity(df, out, pid, knn_pids):

    list_summary = []
    for pid in knn_pids:
        

        i_b = df.iloc[pid]['i_b']
        i = df.iloc[pid]['i']

        ev = out['event_type_list'][i_b][i]
        t = out['event_time_list'][i_b][i]
        st=out['state_time_list'][i_b][i]
        
        P = st.int().max().item() + 1

        M = event2mat(ev,t,P)

        

        vector = M.sum(1)/M.shape[1]*24

        
        list_summary.append(vector)
        

    dotp = [ np.dot(j,list_summary[0])/(np.linalg.norm(j) * np.linalg.norm(list_summary[0])) for  j in list_summary]
    sim_score = np.mean( dotp )


    return sim_score, list_summary




## cif

In [19]:
def plot_cif(out,i_b,i, fig=None):

    ev = out['event_type_list'][i_b][i]
    t = out['event_time_list'][i_b][i]


    tee_att = out['list_TE_att'][i_b][i,:,-4,:] # [h,L]
    cifs = out['list_intens_at_samples'][i_b][i]
    taus = out['list_taus'][i_b][i]

    y_cifs = out['list_true_intens_at_evs'][i_b][i] # [L-1] 2 to L

    P = t.int().max().item() + 1

    m = ev.sum(1)>0 # False are masked
    m = m.sum().item()

    
    taus = taus[:m-1,:,:] + t[:m-1,None,None]
    cifs = cifs[:m-1,:,:]
    y_cifs = y_cifs[:m-1,:]  # 1 to L-1


    n_cifs=cifs.shape[1]
    # print(n_cifs,taus.shape, cifs.shape)

    cifs = cifs.reshape(n_cifs,-1)[0] # [0] is the first cif
    taus = taus.reshape(1,-1)[0]
    y_cifs = y_cifs.reshape(n_cifs,-1)[0]

    print(taus)
    print(cifs)
    # print(n_cifs,taus.shape, cifs.shape)
    temp = torch.argsort(taus)

    taus = taus[temp]
    cifs = cifs[temp]


    if fig==None:
        fig=go.Figure()

    _ = fig.add_trace(go.Scatter(x=taus,y=cifs))

    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=y_cifs*0+1,mode='markers'))
    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=t[1:m],mode='markers'))

    # print(m)
    # print(t[1:5])
    # print(y_cifs[:4])

    _ = fig.add_trace(go.Scatter(x=t[:m],y=t[:m]*0,mode='markers'))

    _ = fig.add_trace(go.Scatter(x=t[1:m],y=y_cifs,mode='markers'))


    

    return fig

In [20]:
def plot_cif_cum(out,i_b,i, fig=None):

    ev = out['event_type_list'][i_b][i]
    t = out['event_time_list'][i_b][i]


    tee_att = out['list_TE_att'][i_b][i,:,-4,:] # [h,L]
    cifs = out['list_intens_at_samples'][i_b][i]
    taus = out['list_taus'][i_b][i]

    y_cifs = out['list_true_intens_at_evs'][i_b][i] # [L-1] 2 to L

    P = t.int().max().item() + 1

    m = ev.sum(1)>0 # False are masked
    m = m.sum().item()

    taus = taus[:m-1,:,:] + t[:m-1,None,None]
    cifs = cifs[:m-1,:,:]
    y_cifs = y_cifs[:m-1,:]  # 1 to L-1


    n_cifs=cifs.shape[1]

    cifs = cifs.reshape(n_cifs,-1)[0]
    taus = taus.reshape(n_cifs,-1)[0]
    y_cifs = y_cifs.reshape(n_cifs,-1)[0]

    temp = torch.argsort(taus)

    taus = taus[temp]
    cifs = cifs[temp]

    cifs_int = integrate.cumulative_trapezoid(cifs, taus, initial=0)/(taus)

    if fig==None:
        fig=go.Figure()

    _ = fig.add_trace(go.Scatter(x=taus,y=cifs_int))

    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=y_cifs*0+1,mode='markers'))
    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=t[1:m],mode='markers'))

    # print(m)
    # print(t[1:5])
    # print(y_cifs[:4])

    _ = fig.add_trace(go.Scatter(x=t[:m],y=t[:m]*0,mode='markers'))

    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=y_cifs,mode='markers'))


    

    return fig

In [21]:
def cif_cum(out,i_b,i, fig=None):

    ev = out['event_type_list'][i_b][i]
    t = out['event_time_list'][i_b][i]


    tee_att = out['list_TE_att'][i_b][i,:,-4,:] # [h,L]
    cifs = out['list_intens_at_samples'][i_b][i]
    taus = out['list_taus'][i_b][i]

    y_cifs = out['list_true_intens_at_evs'][i_b][i] # [L-1] 2 to L

    P = t.int().max().item() + 1

    m = ev.sum(1)>0 # False are masked
    m = m.sum().item()

    taus = taus[:m-1,:,:] + t[:m-1,None,None]
    cifs = cifs[:m-1,:,:]
    y_cifs = y_cifs[:m-1,:]  # 1 to L-1


    n_cifs=cifs.shape[1]

    cifs = cifs.reshape(n_cifs,-1)[0]
    taus = taus.reshape(n_cifs,-1)[0]
    y_cifs = y_cifs.reshape(n_cifs,-1)[0]

    temp = torch.argsort(taus)

    taus = taus[temp]
    cifs = cifs[temp]

    cifs_int = integrate.cumulative_trapezoid(cifs, taus, initial=0)/(taus)

    if fig==None:
        fig=go.Figure()

    _ = fig.add_trace(go.Scatter(x=taus,y=cifs_int))

    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=y_cifs*0+1,mode='markers'))
    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=t[1:m],mode='markers'))

    # print(m)
    # print(t[1:5])
    # print(y_cifs[:4])

    _ = fig.add_trace(go.Scatter(x=t[:m],y=t[:m]*0,mode='markers'))

    # _ = fig.add_trace(go.Scatter(x=t[1:m],y=y_cifs,mode='markers'))


    

    return taus,cifs_int

In [22]:
a=np.arange(6).reshape(2,3)
a

np.roll(a,-1)


array([[0, 1, 2],
       [3, 4, 5]])

array([[1, 2, 3],
       [4, 5, 0]])

## att agg

In [125]:
def jaccard_similarity(row1, row2):
    intersection = np.logical_and(row1, row2).sum()
    union = np.logical_or(row1, row2).sum()
    return intersection / union

def compute_jaccard_similarity(A,B):

    L, M = A.shape
    M, C = B.shape
    res = np.zeros((L, C))
    for i in range(L):
        for j in range(C):
            res[i, j] = jaccard_similarity(A[i], B[:, j])
    return res


def att_map(out,i_b,i,common_patterns):

    # common_patterns is of shape [C,M]

    tee_mapped = np.zeros((common_patterns.shape[0], common_patterns.shape[0])) # [C,C]
    norm = np.zeros((common_patterns.shape[0], common_patterns.shape[0])) # [C,C]

    N_CLUSTERS = common_patterns.shape[0]
    ev = out['event_type_list'][i_b][i].cpu().numpy()   # [L,M]
    
    
    if len(ev.shape)==1:    # if multi-class
        identity = np.eye(common_patterns.shape[1]+1,dtype=np.int8)
        ev = identity.take(ev, axis=0)[:,1:] #  [B,LLLL] -> [B,LLLLLL,K]
    
    m=(ev.sum(1)>0).sum()
    m
    if m==0:
        # print(out['event_time_list'][i_b][i])
        print("NO EVENTS!")
        return tee_mapped, norm
    ev=ev[:m]
    print(ev.shape)

    tee = out['list_TE_att'][i_b][i][:1,:m,:m].mean(0).cpu().numpy() 
    # tee(i,j): influence of j-th event on (i+1)-th event    
    tee[-1,:] = 0
    print(tee[:5,:5])
    scaler=np.arange(1,m+1)[:,None]
    # scaler= (1/tee_att_mat.max(1)[0])[:,None]
    tee *= scaler
    
    tee.shape

    # print(tee.sum(1))



    # print(common_patterns.shape)
    # print(ev.sum(1).shape)
    # print(common_patterns.sum(0).shape)

    # temp_intersect = ev @ common_patterns.T   # [L,n_Cluster]
    # temp_union= np.outer(ev.sum(1), common_patterns.sum(1))-temp_intersect # [L,1][1,N_cluster]
    # print(temp_union.shape, temp_intersect.shape)
    # print(temp_union[0])
    # print(temp_intersect[0])
    # print(temp_intersect[0]/(temp_union[0]+1e-9))

    temp = compute_jaccard_similarity(ev,common_patterns.T) # [L,M],[M,C]->[L,C]

    # print(temp[0])
    # print(ev[0])
    # print(common_patterns)
    # print(temp.shape)

    # print(temp)

    
    temp=np.argmax(temp,axis=1) # [L]
    temp.shape
    temp

    vec_map = temp

    mat_map_1h = np.zeros((m,N_CLUSTERS),dtype= np.int8) # [L,C]
    mat_map_1h[np.arange(m),vec_map]=1
    # print(mat_map_1h.shape)    # [L,N_clusters]

    # IMPORTANT
    mat_iplus1 = np.roll(mat_map_1h.T,-1) # [C,L]
    mat_iplus1[:,-1]=0

    # mat_iplus1 = mat_map_1h.T

    tee_mapped = mat_iplus1 @ tee @ mat_map_1h  # tee_mapped(i,j): influence of j-th pattern on i-th pattern
    tee_mapped.shape

    tee_mapped

    # NEW method
    a=np.einsum('ab,cd->adbc',mat_iplus1,mat_map_1h) # [C,L] [L,C]-> [C,C,L,L]
    q=np.tril(np.ones((m,m),dtype=np.int8)) # [L,L]
    norm=np.sum(  np.einsum('ij,adij->adij',q,a)   ,(-1,-2)) # [C,C]
    # norm=np.einsum('ij,adij->ad',q,a)    # [C,C]

    # OLD method
    # sum1=mat_iplus1.sum(1)  # shape [N_CLUSTER]
    # sum2=mat_map_1h.sum(0)  # shape [N_CLUSTER]
    # norm = np.outer(sum1,sum2)

    # print(norm.shape, norm)


    return tee_mapped, norm

def plot_heatmap_att_agg(df,out,point_ids,fig=None):

    if fig is None:
        fig=go.Figure()

    att_maps=[]
    att_norms=[]
    for pid in point_ids:

        i_b = int(df.iloc[pid]['i_b'])
        i = int(df.iloc[pid]['i'])

        tee_mapped, norm = att_map(out,i_b,i,common_patterns)
        att_maps.append(tee_mapped  )
        att_norms.append(norm  )

    norms_matrix = sum(att_norms)
    norms_matrix[norms_matrix==0]=1
    agg_matrix = sum(att_maps)/norms_matrix
    # agg_matrix[agg_matrix<0.5]=0

    if len(out['event_type_list'][0].shape)==2: # if multi_class
        patt_str = [f'C {i}' for i in range(common_patterns.shape[0])]
    else:
        patt_str = [''.join(str(cell) for cell in row) for row in common_patterns]

    fig = px.imshow(agg_matrix, x=patt_str, y=patt_str)


    return fig

NUM:155
NUM:456
NUM:155
NUM:38
NUM:456
NUM:155
[12, 18, 27, 29, 34, 38, 52, 54, 55, 56, 59, 61, 63, 68, 72, 73, 75, 76, 77, 79, 80, 91, 93, 96, 104, 109, 113, 114, 119, 121, 122, 123, 124, 129, 132, 134, 149, 154, 155, 159, 160, 164, 167, 168, 170, 172, 173, 175, 176, 180, 183, 185, 201, 205, 208, 210, 231, 234, 235, 237, 238, 240, 254, 255, 257, 259, 260, 262, 263, 269, 274, 277, 282, 285, 291, 294, 298, 303, 304, 310, 312, 315, 319, 320, 329, 337, 340, 344, 348, 351, 353, 358, 360, 365, 372, 374, 377, 378, 379, 381, 382, 384, 390, 391, 394, 397, 400, 401, 406, 413, 414, 422, 423, 426, 429, 430, 438, 440, 441, 444, 445, 447, 452, 454, 456, 460, 461, 464, 466, 469, 475, 484, 489, 502, 508, 512, 514, 519, 521, 522, 535, 538, 539, 540, 543, 544, 546, 555, 557, 558, 561, 562, 572, 577, 578, 592, 596, 601, 602, 603, 610, 613, 616, 617, 622, 625, 627, 628, 629, 634, 636, 637, 642, 644, 651, 652, 653, 660, 664, 666, 667, 668, 683, 687, 688, 691, 694, 698, 701, 704, 713, 714, 715, 716, 719, 7

## common patterns

In [106]:

def compute_common_patterns(df,opt):
    METHOD = 'cluster_kmeans'

    common_patterns = []

    N_CLUSTERS = df[METHOD].max()
    
    if opt.data_label=='multiclass':
        common_patterns=np.eye(opt.num_marks,dtype=np.int8)

    else:
        for i in range(N_CLUSTERS):
            temp = df[df[METHOD]==i]['val'].values
            temp = (temp.sum()/temp.shape[0]*100).astype(int)

            temp[temp<30]=0
            temp[temp>=30]=1
            print(temp,'\n')
            common_patterns.append(temp)

        common_patterns = np.array(common_patterns)
    common_patterns.shape

    return common_patterns


# Model path

In [24]:
runs_path=[
# "hokarami/TEEDAM_supervised/5uzxzoxd",
"hokarami/TEEDAM_supervised/sb9zf1mm",
"hokarami/TEEDAM_supervised/hue1qxw4",  # seft [Q10-TE__nextmark-concat]1566371 with label

# "hokarami/TEEDAM_supervised/t43m0t0u", # [Q10-DA__base-concat]1563864

"hokarami/TEEDAM_supervised/9gxq3dgy", # [Q10-TEDA__nextmark-concat]1577576 with label

"hokarami/TEEDAM_supervised/56ecgyrq", # [Q20-TEDA__nextmark-concat]1588433
# "hokarami/TEEDAM_supervised/g4x0ibmk", # [Q20-TE__nextmark-concat]1585936 with label

# "hokarami/TEEDAM_supervised/lzvf7erg", # [Q20-DA__base-concat]1586915

]

run_path = runs_path[-1]
run_path


# run = api.run(run_path)
# for file in run.files():
#     file.download(replace=True,root='./local/')

'hokarami/TEEDAM_supervised/56ecgyrq'

# ATT

In [25]:
# out.keys()
# bs = opt.batch_size


# out['event_type_list'][0].shape
# out['event_time_list'][0].shape
# out['non_pad_mask_list'][0].shape
# out['list_TE_att'][0].shape

# out['state_mod_list'][0].shape
# out['list_DAM_att'][0].shape

# out['y_state_true'].shape




In [26]:
# binary_matrix = state2mat(st, sm,n_state_mods)

# # binary_matrix_to_image(binary_matrix, row_labels=state_labels, font_path=None, grid_size=10, border_size=1, label_size=8)


# M = [state2mat(st, sm,n_state_mods) +  att_state2mat(st, sm, n_state_mods, dam_att.sum(1))*0,
     
#      att_event2mat(ev, t,P, tee_att)*12
     
#      ]

# all_labels = [*state_labels,
#               *[f"Head_{i}" for i in range(tee_att.shape[0])]
#               ]
# binary_matrix = np.concatenate(M, axis=0)

# # binary_matrix_to_image(binary_matrix, row_labels=all_labels, font_path=None, grid_size=10, border_size=1, label_size=8)


# # binary_matrix = event2mat(ev,t,P)
# # event_labels = opt.dict_map_events.keys()

# # binary_matrix_to_image(binary_matrix, row_labels=None, font_path=None, grid_size=10, border_size=1, label_size=8)


# binary_matrix = att_state2mat(st, sm, n_state_mods, dam_att.sum(1))
# img_att = binary_matrix_to_image(binary_matrix, row_labels=state_labels, font_path=None, grid_size=10, border_size=1, label_size=8,is_fill=False,**rgb_params_att)


# binary_matrix = att_state2mat(st, sm, n_state_mods, sv)
# img_val = binary_matrix_to_image(binary_matrix, row_labels=state_labels, font_path=None, grid_size=10, border_size=1, label_size=8,is_fill=True,**rgb_params_values)




In [27]:
# # binary_matrix[binary_matrix!=0].shape
# # binary_matrix.shape
# # binary_matrix.min()
# # binary_matrix.max()

# i_b=3
# i=18

# merged_img,temp = cool_image(out,i_b,i,opt)

# temp[2][0]
# temp[2][1]
# temp[0]
# merged_img

# map_to_rgb(-0)

In [28]:
# if 'y_state_true' in out:

#     y_state_pred = out['y_state_pred']
#     y_state_true = out['y_state_true']
#     y_state_score = out['y_state_score']
# else:
#     y_state_pred = None
#     y_state_true = None
#     y_state_score = None

# y_pred = out['y_pred']
# y_true = out['y_true']
# y_score = out['y_score']


# res=list()


# if len(out['state_mod_list'])>0 and 0:

#     res_labels = opt.dict_map_states.keys()

#     n_cols = len(opt.dict_map_states.keys())

#     state_mod_list = out['state_mod_list']
#     state_time_list = out['state_time_list']
#     len(state_mod_list)
#     state_mod_list[0].shape

#     for state_mod,state_time in zip(state_mod_list,state_time_list):
#         xs = torch.unbind(state_time,0)
#         ys = torch.unbind(state_mod,0)

#         for x,y in zip(xs,ys):
#             # y = y[y~=0]
#             n_rows = x.int().max().item() + 1
#             matrix = torch.zeros(n_rows, n_cols)
#             matrix[x[y!=0].long(), y[y!=0]-1] = 1
#             res.append(matrix.cpu().numpy().transpose()) # [n_marks * times]


# else:
#     non_pad_mask_list = out['non_pad_mask_list']
#     event_type_list = out['event_type_list']
#     event_time_list = out['event_time_list']

#     event_type_list[0].shape
#     non_pad_mask_list[0].shape

#     num_marks = event_type_list[0].shape[-1]
#     res_labels = opt.dict_map_events.keys()



#     for event_type, event_time, non_pad_mask in zip(event_type_list,event_time_list,non_pad_mask_list):

#         B = event_type.shape[0]
#         for i in range(B):
#             m = non_pad_mask[i]
#             e=event_type[i,:m.sum().int(),:]
#             t=event_time[i,:m.sum().int()]
            
#             indices = e.nonzero()
#             indices[:,0] = t[indices[:,0]]

#             M = torch.zeros((indices[:,0].max()+1, e.shape[-1]))
#             M[indices[:,0],indices[:,1]]=1


#             res.append( M.cpu().numpy().astype(np.uint8).transpose() )


#         # temp = torch.unbind(event_type,0)
#         # lens = non_pad_mask.sum(1).long()
#         # term
#         # for i,x in enumerate(temp):
#         #     res.append( x[:lens[i],:].cpu().numpy().astype(np.uint8).transpose() )




# res[1].shape

# len(res_labels)
# res_labels




# # for i,pattern in enumerate(res):
# #     image = Image.fromarray(pattern)


# #     # row_labels = opt.dict_map_states.keys()
# #     # image = binary_matrix_to_image(pattern, row_labels=row_labels, grid_size=50, border_size=2, label_size=20)
# #     # image.save(f'./local/images/img{i}.jpeg')
# all_images = [f'./local/images/img{i}.jpeg' for i in range(len(res))]

# Visualizations

## TSNE of Learned Rep

In [29]:
TSNE_LIMIT = 6000

def compute_tsne(r_enc_list, model):
    tsne = TSNE(n_components=2, perplexity=30, learning_rate=10,n_jobs=4)

    # r_enc_list = out['r_enc_list']

    X = np.concatenate(r_enc_list,axis=0)[:,:]
    X_tsne = tsne.fit_transform(X[:TSNE_LIMIT,:])

    X_tsne_split=dict()
    if model.d_out_te>0:
        X_te = np.concatenate(r_enc_list,axis=0)[:,:model.d_out_te]
        X_te_tsne = tsne.fit_transform(X_te[:TSNE_LIMIT,:])
        X_tsne_split['tee']=X_te_tsne

    if model.d_out_dam>0:    
        X_dam = np.concatenate(r_enc_list,axis=0)[:,model.d_out_te:]
        X_dam_tsne = tsne.fit_transform(X_dam[:TSNE_LIMIT,:])
        X_tsne_split['dam']=X_dam_tsne
    return X_tsne, X_tsne_split

## build df

In [30]:

def build_df(out,opt, X_tsne):
    if 'y_state_true' in out:

        y_state_pred = out['y_state_pred']
        y_state_true = out['y_state_true']
        y_state_score = out['y_state_score']
    else:
        y_state_pred = None
        y_state_true = None
        y_state_score = None

    y_pred = out['y_pred']
    y_true = out['y_true']
    y_score = out['y_score']

    df = pd.DataFrame()
    df['x']=X_tsne[:,0]
    df['y']=X_tsne[:,1]

    # df['x']=X_te_tsne[:,0]
    # df['y']=X_te_tsne[:,1]

    # df['x']=X_dam_tsne[:,0]
    # df['y']=X_dam_tsne[:,1]

    df['color']=0
    df['id']=np.arange(len(df))


    if y_state_true is not None:

        TP = (y_state_true[:TSNE_LIMIT]*y_state_pred[:TSNE_LIMIT])==1
        FN = (y_state_true[:TSNE_LIMIT]-y_state_pred[:TSNE_LIMIT])==1
        FP = (y_state_true[:TSNE_LIMIT]-y_state_pred[:TSNE_LIMIT])==-1

        TN = (y_state_true[:TSNE_LIMIT]+y_state_pred[:TSNE_LIMIT])==0

        FP_FN = (y_state_true[:TSNE_LIMIT]+y_state_pred[:TSNE_LIMIT])==1
        TP_TN = (y_state_true[:TSNE_LIMIT]-y_state_pred[:TSNE_LIMIT])==0


        # df.loc[TN, 'color']='True Negatives'
        df.loc[TP, 'color']='True Positives'
        df.loc[FN, 'color']='False Negatives'
        df.loc[FP, 'color']='False Positives'
        df.loc[TN, 'color']='True Negatives'

        df.loc[TP_TN, 'color_true_pred']='True Predicted'
        df.loc[FP_FN, 'color_true_pred']='False Predicted'


        df.loc[y_state_true[:TSNE_LIMIT].astype(bool).flatten(), 'color_true']='Positive Samples'
        df.loc[~y_state_true[:TSNE_LIMIT].astype(bool).flatten(), 'color_true']='Negative Samples'


        df.loc[y_state_pred[:TSNE_LIMIT].astype(bool).flatten(), 'color_pred']='Positive Predicted'
        df.loc[~y_state_pred[:TSNE_LIMIT].astype(bool).flatten(), 'color_pred']='Negative Predicted'

        # df.loc[y_state_pred[:TSNE_LIMIT].astype(bool).flatten(), 'color_true_pred']='Positive Predicted'
        # df.loc[~y_state_pred[:TSNE_LIMIT].astype(bool).flatten(), 'color_true_pred']='Negative Predicted'


    df['i_b'] = df['id'].apply(lambda x:int(x / opt.batch_size) )
    df['i'] = df['id'].apply(lambda x:x % opt.batch_size)

    t_max = np.concatenate( [t.max(1)[0] for t in out['event_time_list']] )

    df['color_t_max'] = t_max
    if len(out['list_log_sum'])>0:
        df['color_log_sum'] = np.concatenate(out['list_log_sum'],axis=0) / t_max
        df['color_integral_'] = np.concatenate(out['list_integral_'],axis=0) / t_max
    return df

## plot Figure

In [31]:
color_map = {
    'Positive Samples': "#E52B50",
    'Negative Samples': "#3B7A57",
    'True Predicted': "#E52B50",
    'False Predicted': "#3B7A57",

    
    0: "#3B7A57",
    # 'Positive Predicted': "#3DDC84",
    # 'Negative Predicted': "#FFBF00",

    'Positive Predicted': "#E52B50",
    'Negative Predicted': "#3B7A57",

    5: "#915C83",
    'True Positives': "#008000",
    'False Negatives': "#7FFFD4",
    'False Positives': "#E9D66B",
    'True Negatives': "#007FFF",
}

def plot_tsne(df, title=""):

    fig = go.Figure()

    if 'color_true' in df:
        labels = df['color_true'].values
        colors = [color_map[label] for i,label in enumerate(labels)]

        _ = fig.add_trace(
            go.Scatter(
                x=df['x'],
                y=df['y'],
                # z=tsne[:, 2],
                mode='markers',
                marker=dict(
                    # size=2,
                    color=colors,
                )
            )

        )
    else:
        labels = df['color'].values
        colors = [color_map[label] for i,label in enumerate(labels)]

        _ = fig.add_trace(
            go.Scatter(
                x=df['x'],
                y=df['y'],
                # z=tsne[:, 2],
                mode='markers',
                marker=dict(
                    # size=2,
                    color=colors,
                )
            )

        )

    if 'color_pred' in df:
        labels = df['color_pred'].values
        colors = [color_map[label] for i,label in enumerate(labels)]
        _ = fig.add_trace(
            go.Scatter(
                x=df['x'],
                y=df['y'],
                # z=tsne[:, 2],
                mode='markers',
                marker=dict(
                    symbol='circle-open',
                    # size=10,
                    color=colors,
                )
            )

        )

        
    if 'color_integral_' in df:
        colors = df['color_integral_'].values

        _ = fig.add_trace(
            go.Scatter(
                x=df['x'],
                y=df['y'],
                # z=tsne[:, 2],
                mode='markers',
                marker=dict(
                    # size=8,
                    color=colors,
                    colorbar=dict(
                        title="cif_integral"
                    ),
                    colorscale="RdBu",
                )
            )

        )

    if 'color_t_max' in df:
        colors = df['color_t_max'].values

        _ = fig.add_trace(
            go.Scatter(
                x=df['x'],
                y=df['y'],
                # z=tsne[:, 2],
                mode='markers',
                marker=dict(
                    # size=8,
                    color=colors,
                    colorbar=dict(
                        title="t_max"
                    ),
                    colorscale="RdBu",
                )
            )

        )

    _=fig.update_layout(
        # autosize=False,
        title=title,
        width=600,
        height=600,
        showlegend=True,

    )
    _=fig.update_traces(
        hoverinfo="none",
        hovertemplate=None,
    )
    # _=fig.update_layout(
    #     scene=dict(
    #         xaxis=dict(range=[-10,10]),
    #         yaxis=dict(range=[-10,10]),
    #         # zaxis=dict(range=[-10,10]),   
    #     )
    # )





    # save to run
    # fig.write_html(f"local/{run.name}.html")
    # run.upload_file(f"local/{run.name}.html")


    # tsne of TE_nextmark[label]
        # https://storage.googleapis.com/wandb-production.appspot.com/hokarami/TEEDAM_supervised/hue1qxw4/local/temp.html?Expires=1676986614&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=xLOuNCu8qoWVwFRPCspoPKTFbpF5aOSJMAFICqsDRYxf2wfudxEiFFEIlXBIq9YyYZcPtpSKSzYb6nUr0lloLZ6GHg1w4AOBZyieBKBsuKmIDGqhRY4ojK0FPHZHD%2BeoKERgjD42F19vP8E5Qf%2BA7PlgB2E%2BWutwJxx1sc2TtCgjUdkEK%2BEwaTzfQBQ0hXGIWC9MeirU7hRSmn4%2BXzIRaRcUFjF0vOtxCHBjsEhldGSwaUFv21kt4qvr2hSeR5Ku5gS7webtvzVi6fw55Muq78%2FB90r3EqWqy9Sn68T%2FDKx%2F%2FzHVfge4TsxlIjRE%2F9HBCo7qZeNeeHnlHjVZXdvTKg%3D%3D

    # tsne of DA[label]
        # https://storage.googleapis.com/wandb-production.appspot.com/hokarami/TEEDAM_supervised/t43m0t0u/local/temp.html?Expires=1676987035&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=jX44t4Nblmtzd0CCZC2Gn0cw43iZZbZtuofN%2BrlmzgennSxNz36YE4BwYU%2Ft21iuFdSwmqPLnnI%2B2saLWT9kZsBHNo0e2Nsti0vhf7216iT1wsnnFukn%2B8CswPFeQUQBmSyvEO0IJRTE%2BLmjORdY5NFMdgeXchVwLlf8LBIJFoxAfyiaYLmCNcjWwSmbkvVf1DwOxL2sjneA8TtkgQiSCZiC3GgMJBfh8wg1bf6wS%2Bxa95APq%2BPo6J7%2Ffq0sqmqCiAp28E309PlM29C0C89y63dvzqkRhBhvdffx3O%2FFUAmK%2FjRF82ohd7JSgxMva9oWz%2By7aHESGKr0b49KrUxM2Q%3D%3D

    return fig

## Dash

In [85]:

def run_dash_app(fig_tsne,out,opt, df,port=None):
    if port is None:
        port = np.random.randint(2000,5000)

    app = JupyterDash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

    app.layout = dbc.Container([
        # className="container",
        # children=[

            dbc.Row([
                    html.Div(id="dummy2"),
                    html.Div(id="dummy"),
                ]),

            dbc.Row([
                
                dbc.Col(
                    dcc.Graph(id="graph-5", figure=fig_tsne, clear_on_unhover=True,),

                    
                    width=6),  # first column with graph



                dbc.Col([
                    html.Img(id='image_merge',src='./local/images/C0-1296.jpeg',style={"width": "500px", 'display': 'block', 'margin': '0 auto'},),

                    html.Img(id='image_att',src='./local/images/C0-1296.jpeg',style={"width": "500px", 'display': 'block', 'margin': '0 auto'},),

                ], width=6),  # second column with image
            ]),

            # dbc.Row([
            #     dcc.Graph(id="graph-cif", figure=go.Figure(), clear_on_unhover=True,),

        
            # ]),

            dbc.Row([
                dcc.Graph(id="graph-cif", figure=go.Figure(), clear_on_unhover=True,),

        
            ]),

            dbc.Row([
                
                dbc.Col(
                    dcc.Graph(id="graph-att-agg", figure=go.Figure(), clear_on_unhover=True,),

                    
                    width=6),  # first column with graph

                dbc.Col(
                    dcc.Graph(id="graph-summary", figure=go.Figure(), clear_on_unhover=True,),

                    
                    width=6),  # first column with graph

                # dbc.Col(
                #     html.Img(id='image',src='./local/images/C0-1296.jpeg',style={"height": "400px", 'display': 'block', 'margin': '0 auto'},),
                
                
                # width=6),  # second column with image
            ]),

            dcc.Tooltip(id="graph-tooltip-5", direction='bottom'),


        
        ])

    @app.callback(
        # Output("graph-tooltip-5", "show"),
        # Output("graph-tooltip-5", "bbox"),
        # Output("graph-tooltip-5", "children"),
        Output('image_merge', 'src'),
        Output('image_att', 'src'),
        Output("dummy2", "children"),
        Output("graph-cif", "figure"),
        Input("graph-5", "hoverData"),
    )
    def display_hover(hoverData):
        if hoverData is None:
            # return False, no_update, no_update, no_update, no_update
            return no_update,no_update, no_update, no_update

        num = 111111
        # demo only shows the first point, but other points may also be available
        hover_data = hoverData["points"][0]
        bbox = hover_data["bbox"]
        num = hover_data["pointNumber"]

        print(f'NUM:{num}')

        # im_matrix = res[num].astype(int)
        # # im_url = np_image_to_base64(im_matrix)
        # # im_url = binary_matrix_to_image(im_matrix)
        # im_url = binary_matrix_to_image(im_matrix, row_labels=res_labels, grid_size=50, border_size=2, label_size=20)
        



        # # bar plot
        # vector = im_matrix.sum(1)/im_matrix.shape[1]*24
        # # im_url = plot_bar_chart(vector, labels=res_labels)
        # im_url = create_barplot_image(vector, res_labels, './local/images/temp.png')


    

        # NEW
        i_b = int(df.iloc[num]['i_b'])
        i = int(df.iloc[num]['i'])
        im_url, temp = cool_image(out,i_b,i,opt)

        
        output_str = f"{num} - {df.iloc[num]['color']} - i_b {i_b} - i {i}"
        
        im_url.save("./local/images/hover_img.png")
        if temp[0] is not None:
            im_url.save("./local/images/att.png")

        im_url_path = './local/images/C2-203.jpeg'
        
        
        
        children = [
            html.Div([
                html.Img(
                    src=im_url,
                    style={"height": "400px", 'display': 'block', 'margin': '0 auto'},
                ),
                # html.P("MNIST Digit " + str(labels[num]), style={'font-weight': 'bold'})
                html.P(f"Patterns-id={num} - i_b {i_b} - i {i}" , style={'font-weight': 'bold'})

            ])
            
        ]

        fig_cif = plot_cif(out,i_b,i)
        # fig_cif = plot_cif_cum(out,i_b,i)


        # return True, bbox, children,im_url, output_str
        return im_url,temp[0], output_str,fig_cif        # temp[0]





    # Define a callback function to print the selected point IDs
    @app.callback(Output("dummy", "children"),Output("graph-summary", "figure"), Output("graph-att-agg", "figure"), [Input("graph-5", "selectedData"), Input("graph-summary", "figure")])
    def display_selected_data(selected_data, fig_prev):
        if selected_data is None:
            return "No points selected.",no_update,no_update
        else:


            new_fig = go.Figure(data=fig_prev['data'],layout=fig_prev['layout'])
            fig_att_agg = go.Figure(data=fig_prev['data'],layout=fig_prev['layout'])


            point_ids = [point["pointIndex"] for point in selected_data["points"]]

            # new_fig = bar_summary(df,out, point_ids,res_labels, fig=new_fig)
            
            print(point_ids)
            fig_att_agg = plot_heatmap_att_agg(df,out,point_ids)

            # # save selected to local
            # for pid in point_ids:
            #     # NEW
            #     i_b = df.iloc[pid]['i_b']
            #     i = df.iloc[pid]['i']
            #     im_url, temp = cool_image(out,i_b,i,opt)
            #     im_url.save(f"./local/images/selected{pid}.png")

            # print(f"{point_ids},\n")
            return f"{point_ids},\n",new_fig,fig_att_agg

    if __name__ == "__main__":
        # app.run_server(mode='inline', debug=True)
        app.run_server(mode='external',port=port)

# TEDAM

In [111]:
run_path = "hokarami/TEEDAM_supervised/56ecgyrq" # [Q20-TEDA__nextmark-concat]1588433
run_path = "hokarami/TEEDAM_supervised/3x52mwgi" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/3x52mwgi/overview?workspace=user-g-hojatkarami
run_path = "hokarami/TEEDAM_unsupervised/ibzmm7wm" # https://wandb.ai/hokarami/TEEDAM_unsupervised/runs/ibzmm7wm/overview?workspace=
# run_path = "hokarami/TEEDAM_supervised/v1nb7bhq" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/v1nb7bhq/overview?workspace=user-g-hojatkarami
run_path = "hokarami/TEEDAM_unsupervised/jvpugrlq" # https://wandb.ai/hokarami/TEEDAM_unsupervised/runs/jvpugrlq/overview?workspace=user-g-hojatkarami


run_path = "hokarami/TEEDAM_unsupervised/a95wkhvj" # https://wandb.ai/hokarami/TEEDAM_unsupervised/runs/a95wkhvj/overview?workspace=user-g-hojatkarami
run_path = "hokarami/TEEDAM_supervised/e2ty765j" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/e2ty765j/overview?workspace=user-g-hojatkarami

# h0s0
run_path = "hokarami/TEEDAM_supervised/noufk1a0" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/noufk1a0/overview?workspace=user-g-hojatkarami

# seft
run_path = "hokarami/TEEDAM_supervised/g0g8zo1n" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/g0g8zo1n/overview?workspace=user-g-hojatkarami

# unsup
run_path = "hokarami/TEEDAM_unsupervised/fyn5cxoi" # https://wandb.ai/hokarami/TEEDAM_unsupervised/runs/fyn5cxoi/overview?workspace=user-g-hojatkarami

run_path = "hokarami/TEEDAM_supervised/g0g8zo1n" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/g0g8zo1n/overview?workspace=user-g-hojatkarami




# p19
run_path = "hokarami/TEEDAM_supervised/ah1p114x" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/ah1p114x?workspace=user-g-hojatkarami


# p12 unsup TE only
run_path = "hokarami/TEEDAM_unsupervised/0k296zum" # https://wandb.ai/hokarami/TEEDAM_unsupervised/runs/0k296zum/overview?workspace=user-g-hojatkarami


model1, opt1, run1 = read_from_wandb(run_path)
dict_metrics1, out1 = Main.valid_epoch_tsne(model1, opt1.validloader, opt1.pred_loss_func, opt1)
X_tsne1, X_tsne_split1 = compute_tsne(out1['r_enc_list'], model1)

res_labels = opt1.dict_map_events.keys()

df1 = build_df(out1,opt1, X_tsne1)
fig_tsne1 = plot_tsne(df1,title=run1.name)


############################## CUDA True
[Info] INPUT TE --> none-mark
[Info] parameters: Namespace(data='/mlodata1/hokarami/tedam/p12-mc1-H1/split2/', data_label='multilabel', cuda=1, wandb=True, wandb_project='TEEDAM_unsupervised', log_freq=1, prof=False, per=100, balanced_batch=True, transfer_learning='', freeze='', ES_pat=100, setting='mc1', test_center='1', split='2', log='log.txt', user_prefix='[H10-TE__nextmark-concat]', pos_alpha=1.0, epoch=50, batch_size=128, lr=0.01, smooth=0.0, weight_decay=0.1, event_enc=1, time_enc='concat', te_d_mark=32, te_d_time=16, te_d_rnn=256, te_d_inner=128, te_d_k=32, te_d_v=32, te_n_head=4, te_n_layers=4, te_dropout=0.1, state=False, demo=False, num_states=1, noise=False, mod='none', int_dec='sahp', w_event=1.0, next_mark=1, w_class=False, w_pos=False, mark_detach=0, w_time=1.0, sample_label=0, w_pos_label=1.0, w_sample_label=100.0, hparams2write={'data': '/mlodata1/hokarami/tedam/p12/', 'data_label': 'multilabel', 'cuda': 1, 'wandb': True, 'wandb

In [ ]:
df_temp = build_df(out1,opt1, X_tsne1)
fig_temp = plot_tsne(df_temp,title=run1.name)
fig_temp


df_temp = build_df(out1,opt1, X_tsne_split1['dam'])
fig_temp = plot_tsne(df_temp,title=run1.name)
fig_temp

df_temp = build_df(out1,opt1, X_tsne_split1['tee'])
fig_temp = plot_tsne(df_temp,title=run1.name)
fig_temp

In [56]:
df1.dtypes
len(df1)
df1.i.dtypes
print('dfd')
df1.iloc[146]
df1.iloc[146].dtypes

i_b = df1.iloc[146]['i_b']
i = df1.iloc[146]['i']
print('hhhhhhhhhhhh',146,i_b,i)

x              float32
y              float32
color            int64
id               int64
i_b              int64
i                int64
color_t_max    float32
dtype: object

768

dtype('int64')

dfd


x                8.176332
y               38.434216
color            0.000000
id             146.000000
i_b              1.000000
i               18.000000
color_t_max     39.150002
Name: 146, dtype: float64

dtype('float64')

hhhhhhhhhhhh 146 1.0 18.0


In [112]:
df1 = build_df(out1,opt1, X_tsne1)
fig_tsne1 = plot_tsne(df1,title=run1.name)

run_dash_app(fig_tsne1,out1,opt1,df1)


Dash app running on http://127.0.0.1:4379/


# DAM

In [ ]:
run_path =  "hokarami/TEEDAM_supervised/lzvf7erg" # [Q20-DA__base-concat]1586915



run_path = "hokarami/TEEDAM_unsupervised/su87zi5z" # https://wandb.ai/hokarami/TEEDAM_unsupervised/runs/su87zi5z/overview?workspace=user-g-hojatkarami

# h0s0
run_path = "hokarami/TEEDAM_supervised/bxawmk71" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/bxawmk71/overview?workspace=user-g-hojatkarami

# seft
run_path = "hokarami/TEEDAM_supervised/qvdve9d5" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/qvdve9d5?workspace=user-g-hojatkarami

# seft
run_path = "hokarami/TEEDAM_supervised/qvdve9d5" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/qvdve9d5?workspace=user-g-hojatkarami


# so
# run_path = "hokarami/TEEDAM_unsupervised_timeCat/22xvwu9y" # https://wandb.ai/hokarami/TEEDAM_unsupervised/runs/su87zi5z/overview?workspace=user-g-hojatkarami


# p19
run_path =  "hokarami/TEEDAM_supervised/yftm62nl" # https://wandb.ai/hokarami/TEEDAM_supervised/runs/yftm62nl?workspace=user-g-hojatkarami



model2, opt2, run2 = read_from_wandb(run_path)
dict_metrics2, out2 = Main.valid_epoch_tsne(model2, opt2.validloader, opt2.pred_loss_func, opt2)
X_tsne2, X_tsne_split2 = compute_tsne(out2['r_enc_list'], model2)

# res_labels = opt2.dict_map_events.keys()

df2 = build_df(out2,opt2, X_tsne2)
fig_tsne2 = plot_tsne(df2,title=run2.name)

In [ ]:
df_temp = build_df(out2,opt2, X_tsne2)
fig_temp = plot_tsne(df_temp,title=run2.name)
fig_temp




In [ ]:




run_dash_app(fig_tsne2,out2,opt2,df2)





# SO

In [33]:
run_path = "hokarami/TEEDAM_unsupervised_timeCat/3u09b0nt" # https://wandb.ai/hokarami/TEEDAM_unsupervised_timeCat/runs/3u09b0nt/overview?workspace=user-g-hojatkarami


model3, opt3, run3 = read_from_wandb(run_path)
dict_metrics3, out3 = Main.valid_epoch_tsne(model3, opt3.validloader, opt3.pred_loss_func, opt3)
X_tsne3, X_tsne_split3 = compute_tsne(out3['r_enc_list'], model3)

if hasattr(opt3,'dict_map_events'):
    res_labels = opt3.dict_map_events.keys()

df3 = build_df(out3,opt3, X_tsne3)
fig_tsne3 = plot_tsne(df3,title=run3.name)


############################## CUDA True
[Info] INPUT TE --> none-mark
[Info] parameters: Namespace(data='/mlodata1/hokarami/tedam/data_so/split0/', data_label='multiclass', cuda=1, wandb=True, wandb_project='TEEDAM_unsupervised_timeCat', log_freq=1, prof=False, per=100, balanced_batch=True, transfer_learning='', freeze='', ES_pat=100, setting='', test_center='', split='0', log='log.txt', user_prefix='[TEST-DEB-DIAGS-TE__nextmark-concat]', pos_alpha=1.0, epoch=1, batch_size=4, lr=0.001, smooth=0.0, weight_decay=0.1, diag_offset=-3, event_enc=1, time_enc='concat', te_d_mark=32, te_d_time=16, te_d_rnn=256, te_d_inner=128, te_d_k=32, te_d_v=32, te_n_head=4, te_n_layers=4, te_dropout=0.1, state=False, demo=False, num_states=1, noise=False, mod='none', int_dec='sahp', w_event=1.0, next_mark=1, w_class=False, w_pos=False, mark_detach=0, w_time=1.0, sample_label=0, w_pos_label=1.0, w_sample_label=10000.0, hparams2write={'data': '/mlodata1/hokarami/tedam/data_so/', 'data_label': 'multiclass', 

In [86]:
df3 = build_df(out3,opt3, X_tsne3)
fig_tsne3 = plot_tsne(df3,title=run3.name)

run_dash_app(fig_tsne3,out3,opt3,df3)


Dash app running on http://127.0.0.1:4325/


NUM:60
NUM:245
[3, 6, 8, 22, 23, 27, 48, 53, 61, 69, 72, 95, 99, 100, 101, 103, 105, 111, 122, 151, 169, 189, 197, 204, 219, 234, 250, 263, 285, 306, 329, 332, 338, 341, 348, 349, 350, 362, 372, 373, 396, 401, 404, 409, 417, 444, 458, 461, 463, 472, 480, 483, 486, 488, 495, 501, 506, 510, 511, 521]
(97,)
97
(97, 22)
[[0.01030928 0.01030928 0.01030928 0.01030928 0.01030928]
 [0.01030928 0.01030928 0.01030928 0.01030928 0.01030928]
 [0.01030928 0.01030928 0.01030928 0.01030928 0.01030928]
 [0.01030928 0.01030928 0.01030928 0.01030928 0.01030928]
 [1.         0.         0.         0.         0.        ]]
NUM:45
NUM:317
(66,)
66
(66, 22)
[[0.01515152 0.01515152 0.01515152 0.01515152 0.01515152]
 [0.01515152 0.01515152 0.01515152 0.01515152 0.01515152]
 [0.01515152 0.01515152 0.01515152 0.01515152 0.01515152]
 [0.01515152 0.01515152 0.01515152 0.01515152 0.01515152]
 [1.         0.         0.         0.         0.        ]]
(141,)
141
(141, 22)
[[0.0070922 0.0070922 0.0070922 0.0070922 0.00

# plot subset

In [ ]:
pid=90
i_b = int(df1.iloc[pid]['i_b'])
i = int(df1.iloc[pid]['i'])
i_b,i
_,temp = cool_image(out1,i_b,i,opt1)
temp[0]


fig_cif = plot_cif(out1,i_b,i)
fig_cif

In [ ]:
out1.keys()
out1['next_event_type_list'][10][94].shape
out1['event_type_list'][10][94].shape

## K nearest

In [ ]:
df1.head(2)
df2.head(2)

## knn-ps

In [ ]:
n_knn=5
pid_all = list(df1.index)

pid_positive = list(df1[df1.color_true=='Positive Samples'].index)

list_sim_score1 = []
list_sim_score2 = []

X1 = np.concatenate(out1['r_enc_list'],axis=0)[:,:model1.d_out_te]
X2 = np.concatenate(out2['r_enc_list'],axis=0)[:,:]

for pid in tqdm( pid_positive ):
    id_origin = pid

    knn_pids = find_knn_pids (X1, id_origin, n_knn=n_knn)
    sim_score1, list_summary = cal_similarity(df1, out1, pid, knn_pids)    


    knn_pids = find_knn_pids (X2, id_origin, n_knn=n_knn)
    sim_score2, list_summary = cal_similarity(df2, out2, pid, knn_pids)    
    
    if ( not np.isnan(sim_score1) ) and ( not np.isnan(sim_score2) ):
        list_sim_score1.append(sim_score1)
        list_sim_score2.append(sim_score2)

In [ ]:
np.mean(list_sim_score1), np.std(list_sim_score1)
np.mean(list_sim_score2), np.std(list_sim_score2)

diff = np.array(list_sim_score1) - np.array(list_sim_score2)
diff.sum()/len(diff)
diff.argsort()


In [ ]:
from scipy.stats import ttest_ind


group1 = [x-0.0 for x in list_sim_score1]
group2 = list_sim_score2
t_statistic, p_value = ttest_ind(group1, group2, alternative='greater')

# Print the results
print('t-statistic =', t_statistic)
print('p-value =', p_value)

## plot knn

In [ ]:
# # save selected to local
n_knn=5
id_origin = 90

len_CROP = len(opt1.dict_map_states.keys()) - len(opt1.dict_map_events.keys())
len_CROP

X1 = np.concatenate(out1['r_enc_list'],axis=0)[:,:model1.d_out_te]
X2 = np.concatenate(out2['r_enc_list'],axis=0)[:,:]


            # plot and save id_origin
i_b = df1.iloc[id_origin]['i_b']
i = df1.iloc[id_origin]['i']
im_url, temp = cool_image(out1,i_b,i,opt1)
im_url.save(f"./local/images/Origin_{id_origin}.png")

            # save event attentions
_,temp = cool_image(out1,i_b,i,opt1)
temp[0].save(f"./local/images/Origin_{id_origin}_att.png")

            # save cif plot
fig_cif = plot_cif(out1,i_b,i)
fig_cif.write_image(f"./local/images/Origin_{id_origin}_CIF.svg")


i_g=0
for out,opt,df,X in zip([out1,out2],[opt1,opt2],[df1,df2],[X1,X2]):
    knn_pids = find_knn_pids (X, id_origin, n_knn=n_knn)
    knn_pids
    for pid in knn_pids:
        # NEW
        i_b = df.iloc[pid]['i_b']
        i = df.iloc[pid]['i']
        im_url, temp = cool_image(out,i_b,i,opt,CROP=len_CROP)
        im_url.save(f"./local/images/C{i_g}_{pid}.png")



    i_g+=1

## cif diff

$log(\lambda)$

In [ ]:

pid_positive = list(df1[df1.color_true=='Positive Samples'].index)
pid_negative = list(df1[df1.color_true=='Negative Samples'].index)

list_sim_score1 = []
list_sim_score2 = []

lens = np.concatenate([x.sum(1).cpu().detach() for x in out1['non_pad_mask_list']])
X = np.concatenate(out1['list_log_sum'],axis=0) # [n_samples]
Y = np.concatenate(out1['list_integral_'],axis=0)/lens # [n_samples]


X[pid_positive].mean(), X[pid_positive].std()

X[pid_negative].mean(), X[pid_negative].std()



Y[pid_positive].mean(), Y[pid_positive].std()

Y[pid_negative].mean(), Y[pid_negative].std()


In [ ]:
from scipy.stats import ttest_ind


group1 = X[pid_positive]
group2 = X[pid_negative]
t_statistic, p_value = ttest_ind(group1, group2, alternative='greater')

# Print the results
print('t-statistic =', t_statistic)
print('p-value =', p_value)


group1 = Y[pid_positive]
group2 = Y[pid_negative]
t_statistic, p_value = ttest_ind(group1, group2, alternative='greater')

# Print the results
print('t-statistic =', t_statistic)
print('p-value =', p_value)

integral

In [ ]:

clusters = [

[1715, 1212, 957, 834, 1401, 1532, 33, 514, 559, 1493],
[1715, 1542, 808, 957, 1541, 1296, 252, 978, 34, 1204]



]



df = df1
out = out1

fig2 = go.Figure()
for i_c, cluster in enumerate(clusters):
    list_summary = []
    for pid in cluster:
        

        i_b = df.iloc[pid]['i_b']
        i = df.iloc[pid]['i']

        ev = out['event_type_list'][i_b][i]
        t = out['event_time_list'][i_b][i]
        st=out['state_time_list'][i_b][i]
        
        P = st.int().max().item() + 1

        M = event2mat(ev,t,P)

        

        vector = M.sum(1)/M.shape[1]*24

        
        list_summary.append(vector)
        

    dotp = [ np.dot(j,list_summary[0])/(np.linalg.norm(j) * np.linalg.norm(list_summary[0])) for  j in list_summary]
    np.mean( dotp )

    vec_mean = np.mean(list_summary,axis=0)
    vec_std = np.std(list_summary,axis=0)

    # sum(vec_std)

    
    _ = fig2.add_trace(go.Bar(
        name=f'Cluster {i_c}',
        x=list(res_labels), y=vec_mean,
        error_y=dict(type='data', array=vec_std)
    ))

fig2.show()

## save

In [ ]:
fig_tsne1.write_image("local/images/fig1.svg")
fig_tsne2.write_image("local/images/fig2.svg")

In [ ]:
# # save selected to local
n_knn=5
id_origin = 420

X1 = np.concatenate(out1['r_enc_list'],axis=0)[:,:model1.d_out_te]
X2 = np.concatenate(out2['r_enc_list'],axis=0)[:,:]

i_g=0
for out,opt,df,X in zip([out1,out2],[opt1,opt2],[df1,df2],[X1,X2]):
    
    knn_pids = find_knn_pids (X, id_origin, n_knn=n_knn)
    knn_pids
    # for pid in knn_pids:
    #     # NEW
    #     i_b = df.iloc[pid]['i_b']
    #     i = df.iloc[pid]['i']
    #     im_url, temp = cool_image(out,i_b,i,opt,CROP=11)
    #     # im_url.save(f"./local/images/C{i_g}_{pid}.png")
    i_g+=1

In [ ]:
new_fig =  go.Figure()
# new_fig = go.Figure(data=fig_prev['data'],layout=fig_prev['layout'])


# new_fig = bar_summary(df,out, point_ids,res_labels, fig=new_fig)

n_knn=5
id_origin = 583

X1 = np.concatenate(out1['r_enc_list'],axis=0)[:,:model1.d_out_te]
X2 = np.concatenate(out2['r_enc_list'],axis=0)[:,:]

new_fig = bar_summary(df,out, [id_origin],res_labels, fig=new_fig)

for out,opt,df,X in zip([out1,out2],[opt1,opt2],[df1,df2],[X1,X2]):
    knn_pids = find_knn_pids (X, id_origin, n_knn=n_knn)
    
    new_fig = bar_summary(df,out, knn_pids,res_labels, fig=new_fig)

new_fig
new_fig.write_image("local/images/bar.svg")

# CIF vis

In [ ]:
df=df1
out=out1
pid_positive = list(df1[df1.color_true=='Positive Samples'].index)
pid_negative = list(df1[df1.color_true=='Negative Samples'].index)



fig=go.Figure()

for pid in pid_positive[:50]:

    i_b = int(df.iloc[pid]['i_b'])
    i = int(df.iloc[pid]['i'])
    taus,cifs_int = cif_cum(out1,i_b,i, fig=None)
    _ = fig.add_trace(go.Scatter(x=taus,y=cifs_int,marker=dict(
                    # size=2,
                    color='red',
                )))
    
for pid in pid_negative[:50]:

    i_b = int(df.iloc[pid]['i_b'])
    i = int(df.iloc[pid]['i'])
    taus,cifs_int = cif_cum(out1,i_b,i, fig=None)
    _ = fig.add_trace(go.Scatter(x=taus,y=cifs_int,marker=dict(
                    # size=2,
                    color='blue',
                )))


_=fig.update_layout(
        # autosize=False,
        # title=title,
        width=600,
        height=600,
        showlegend=False,

    )

fig

In [ ]:
opt1.dict_map_events.keys()


for i,k in enumerate(opt1.dict_map_events.keys()):
    print(f'{i}:{k}')

# Attention Aggregation

In [119]:
out=out1
opt=opt1
out.keys()


all_events=np.concatenate(out['event_type_list'],axis=1) # [B,LLLLLL,K] or [B,LLLL]

if opt.data_label=='multiclass':
    identity = np.eye(opt.num_marks+1,dtype=np.int8)
    all_events = identity.take(all_events, axis=0)[:,:,1:] #  [B,LLLL] -> [B,LLLLLL,K]



all_events.shape
masks=all_events.sum(-1)>0



TSNE_LIMIT=16000
X = all_events[masks][:TSNE_LIMIT]


X_str = [''.join(str(cell) for cell in row) for row in X]

X.shape
len(X_str)

df=pd.DataFrame()
df['val']=list(X)
df['str']=X_str
df


dict_keys(['non_pad_mask_list', 'event_type_list', 'event_time_list', 'next_event_type_list', 'list_intens_at_samples', 'list_taus', 'list_true_intens_at_evs', 'list_log_sum', 'list_integral_', 'state_mod_list', 'state_time_list', 'state_value_list', 'r_enc_list', 'list_TE_att', 'list_DAM_att', 'y_pred', 'y_true', 'y_score', 'y_true_list', 'masks'])

(128, 413, 24)

(16000, 24)

16000

val  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...   
4      [1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, ...   
...                                                  ...   
15995  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
15996  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...   
15997  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, ...   
15998  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ...   
15999  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                            str  
0      000000000001110000000000  
1      000000000010000000000000  
2      000000000001110000000000  
3      000000000010000000000000  
4      110100011000000000000000  
...                         ...  
15995  000000000000000000001000  
15996  000000000010000000000000  
15997  000000000001111000000000  
15998  111111111100000111110000  
15999  000000000000000000001000  

[16000 rows x 2 columns]

In [120]:


tsne = TSNE(n_components=2, perplexity=60, learning_rate=10,n_jobs=4)
X_tsne = tsne.fit_transform(X[:TSNE_LIMIT,:])

df['x']=X_tsne[:,0]
df['y']=X_tsne[:,1]

In [121]:
len(df['str'].unique())

s = df['str'].value_counts()/df['str'].value_counts().sum()
s[s>0.001].head(5)

401

000000000010000000000000    0.378250
000000000001110000000000    0.165625
000000000001111000000000    0.078187
000000000000000000001000    0.063187
111111111100000000000000    0.060187
Name: str, dtype: float64

## k-means

In [122]:
from sklearn.cluster import KMeans,AgglomerativeClustering,DBSCAN
import numpy as np

N_CLUSTERS=22

# Generate sample binary data
data = X

# Initialize KMeans object with 2 clusters
kmeans = KMeans(n_clusters=N_CLUSTERS)

# Fit the data to the KMeans object
_ = kmeans.fit(data)

# Get the labels and cluster centers
labels = kmeans.labels_
centers = kmeans.cluster_centers_

labels



df['cluster_kmeans']=labels

fig=px.scatter(df,x='x',y='y',color='cluster_kmeans',hover_data=["str"])
fig


/opt/conda/envs/paper2022/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



array([2, 0, 2, ..., 6, 4, 5], dtype=int32)

## DBSCAN

In [ ]:



# Initialize DBSCAN object
dbscan = DBSCAN(eps=0.5, min_samples=5)

# Fit the data to the DBSCAN object
dbscan.fit(data)

# Get the labels
labels = dbscan.labels_

df['cluster_dbscan']=labels

fig=px.scatter(df,x='x',y='y',color='cluster_dbscan',hover_data=["str"])
fig.show()

## agg

In [123]:
METHOD = 'cluster_kmeans'

common_patterns = []


if opt.data_label=='multiclass':
    common_patterns=np.eye(opt.num_marks,dtype=np.int8)

else:
    for i in range(N_CLUSTERS):
        temp = df[df[METHOD]==i]['val'].values
        temp = (temp.sum()/temp.shape[0]*100).astype(int)

        temp[temp<30]=0
        temp[temp>=30]=1
        print(temp,'\n')
        common_patterns.append(temp)

    common_patterns = np.array(common_patterns)
common_patterns.shape


[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0] 

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0] 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0] 

[0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0] 

[0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] 

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1] 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0] 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0] 

[1 1 0 1 1 0

(22, 24)

[10, 14, 28, 33, 45, 48, 65, 66, 82, 84, 90, 117, 126, 131, 133, 135, 142, 147, 156, 157, 213, 233, 256, 299, 307, 316, 321, 336, 341, 345, 346, 350, 352, 356, 362, 367, 392, 420, 435, 437, 439, 448, 458, 474, 492, 493, 504, 527, 552, 563, 583, 612, 641, 654, 661, 692, 702, 721, 728, 740, 756, 758]
(26, 24)
[[1.         0.         0.         0.         0.        ]
 [0.49999988 0.5000001  0.         0.         0.        ]
 [0.34970555 0.34970573 0.30058873 0.         0.        ]
 [0.26888272 0.26888272 0.23111728 0.23111728 0.        ]
 [0.18990366 0.18990386 0.13727817 0.13727804 0.34563634]]
(9, 24)
[[1.         0.         0.         0.         0.        ]
 [0.5        0.5        0.         0.         0.        ]
 [0.33333343 0.33333343 0.33333313 0.         0.        ]
 [0.25909927 0.25909927 0.25909892 0.22270255 0.        ]
 [0.18054743 0.18054743 0.18054707 0.13050747 0.32785052]]
(20, 24)
[[1.         0.         0.         0.         0.        ]
 [0.5377698  0.46223018 0.        

In [104]:
i_b=9
i=3

att_map(out3,i_b,i,common_patterns)

(68, 22)
[[0.00793651 0.00793651 0.00793651 0.00793651 0.00793651]
 [0.00793651 0.00793651 0.00793651 0.00793651 0.00793651]
 [0.00793651 0.00793651 0.00793651 0.00793651 0.00793651]
 [0.00793651 0.00793651 0.00793651 0.00793651 0.00793651]
 [1.         0.         0.         0.         0.        ]]


(array([[6.6220313e-01, 0.0000000e+00, 0.0000000e+00, 6.3208282e+01,
         2.2699986e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         2.2702299e+01, 0.0000000e+00, 0.0000000e+00, 2.1572199e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
         0.0000000e+00,